#!/bin/bash
./gradlew clean
./gradlew bootJar
docker rm --force wildberries
docker build -t wildberries --pull=true --file=Dockerfile  ./
docker run --publish 8080:8080 --detach --name wildberries wildberries